resume/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^resume/', include('resume_prac.urls',namespace='resume')),
]

urlpatterns += static('uploads', document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

resume_prac/urls.py
# resume_prac/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.resume_list, name='list'),
    url(r'^write$', views.resume_write, name='write'),
    url(r'^write2/(?P<resume_id>\d+)$', views.resume_write_2, name='write2'),
    url(r'^write3/(?P<resume_id>\d+)$', views.resume_write_3, name='write3'),
    url(r'^(?P<resume_id>\d+)$',views.resume_detail,name="detail"),
    url(r'^search/$',views.resume_search,name="search"),
    url(r'^(?P<resume_id>\d+)/add$',views.detail_add,name="detail_add"),
    url(r'^example/(?P<example_id>\d+)$',views.resume_templates,name="example"),
]

resume_prac/models.py
from django.db import models
import json

# Create your models here.


class Person(models.Model) :
	person_name = models.CharField(max_length=80)
	position = models.CharField(max_length=200)
	profile_image = models.ImageField(upload_to='%Y/%m/%d/orig',default='default.png')
	person_desc = models.TextField(blank=True, null=True)
	person_oneline = models.CharField(max_length=80, blank=True, null=True)
	tag_set = models.ManyToManyField('Tag',blank=True)
	fb_url = models.TextField(blank=True,null=True,default='#') # 페이스북 url
	gb_url = models.TextField(blank=True,null=True,default='#') # github url

	def __str__(self):
		return self.person_name

class Skill(models.Model) :
	devstack = models.CharField(max_length=80)
	degree = models.IntegerField(default=0)
	person = models.ForeignKey(Person, on_delete=models.CASCADE)

	def __str__(self):
		return self.devstack

DEFAULT_PERSON_ID = 1
class Experience(models.Model) :
	startDate = models.DateField(blank=True)
	endDate = models.DateField(blank=True)
	publishDate = models.DateField(auto_now=True)
	ex_name = models.CharField(max_length=120)
	ex_desc = models.TextField(blank=True, null=True) # 경험/경력에 대한 설명
	ex_sub = models.TextField(blank=True, null=True)
	person = models.ForeignKey('Person', on_delete=models.CASCADE, default=DEFAULT_PERSON_ID)

	def __str__(self):
		return self.ex_name

class Tag(models.Model) :
	tag_name = models.CharField(max_length=120)

	def __str__(self):
		return self.tag_name

resume_prac/views.py
from django.shortcuts import render
from .models import Person,Skill,Experience,Tag
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.db.models import Q
import datetime
import os

# Create your views here.
def resume_list(request):
    resume_list = Person.objects.all()
    return render(request,'resume_prac/resume_list.html',{'resume_list':resume_list})

def resume_write(request):
    # UPLOAD_DIR = '%Y/%m/%d/orig'

    if request.method == 'POST':
        name = request.POST['name']
        position = request.POST['position']

        oneline = request.POST['oneline']
        intro = request.POST['introduction']

        fb = request.POST['fb']
        gb = request.POST['gb']

        # tags = request.POST.getlist('tags')
        if 'profile_image' in request.FILES :
            profile = request.FILES['profile_image']
            person = Person.objects.create(person_name=name,position=position,profile_image=profile,person_desc=intro,person_oneline=oneline,fb_url=fb,gb_url=gb)
            person.save()
        else :
            person = Person.objects.create(person_name=name,position=position,person_desc=intro,person_oneline=oneline,fb_url=fb,gb_url=gb)
            person.save()

        return HttpResponseRedirect(reverse('resume:write2', args=(person.id,)))
        # return HttpResponseRedirect(reverse('resume:detail', args=(person.id,)))
    else :
         return render(request,'resume_prac/resume_write.html')

def resume_write_2(request,resume_id):

    if request.method == 'POST' :
        person = Person.objects.get(id=resume_id)
        #경력
        ex_startdate = dict(request.POST)['startDate']
        ex_enddate = dict(request.POST)['endDate']
        ex_title = dict(request.POST)['title']
        ex_desc = dict(request.POST)['desc']
        num = 0

        for e in ex_title :
            experience = Experience.objects.create(startDate=ex_startdate[num],endDate= ex_enddate[num],ex_name=e,ex_desc=ex_desc[num],person=person)
            experience.save()
            num+= 1

        return HttpResponseRedirect(reverse('resume:write3', args=(person.id,)))
    else :
        return render(request,'resume_prac/resume_write_2.html')

def resume_write_3(request,resume_id):

    if request.method == 'POST' :
        person = Person.objects.get(id=resume_id)
        #기술 스택
        sk = dict(request.POST)['skill']
        degree = dict(request.POST)['skill_degree']
        number = 0
        for s in sk  :
            skill = Skill.objects.create(devstack=s,person= person,degree=degree[number])
            skill.save()
            number+= 1

        return HttpResponseRedirect(reverse('resume:detail', args=(person.id,)))
    else :
        return render(request,'resume_prac/resume_write_3.html')

def detail_add(request,resume_id):

    if request.method == 'POST':
        person = Person.objects.get(id=resume_id)
        tag_name = dict(request.POST)['tag_name']

        for t in tag_name:
            tag = Tag.objects.create(tag_name=t)
            person.tag_set.add(tag)

        return HttpResponseRedirect(reverse('resume:detail', args=(person.id,)))
    else :
         tag = Tag.objects.all
         return render(request,'resume_prac/detail_add.html',{'tag':tag})

def resume_detail(request,resume_id):
    person = Person.objects.get(id=resume_id)
    experience = person.experience_set.order_by('-startDate')
    return render(request,'resume_prac/resume_detail.html',{'person':person,'experience':experience})

# def resume_detail2(request,resume_id):
#     person = Person.objects.get(id=resume_id)
#     experience = person.experience_set.order_by('-startDate')
#     return render(request,'resume_prac/resume_detail2.html',{'person':person,'experience':experience})

def resume_templates(request,example_id):
    person = Person.objects.first()
    experience = person.experience_set.order_by('-startDate')
    if example_id == "1":
        # == 1 로 했을땐 안됐는데 "1"로 하니까 됐음
        return render(request,'resume_prac/resume_detail.html',{'person':person,'experience':experience})
    else :
        return render(request,'resume_prac/resume_detail_2.html',{'person':person,'experience':experience})

def resume_search(request):
    if request.method =="GET":
        query = request.GET.get('q')
        person = Person.objects.filter(Q(person_name__icontains=query) | Q(position__icontains=query))
        return render(request,'resume_prac/resume_list.html',{'resume_list':person})

resume_prac/templates/resume_prac/detail_add.html
{% extends "resume_prac/header.html" %}
{% load staticfiles %}

<html>
<head>
    <title>관심사 추가</title>



  {% block extra_head %}
  <script>

  window.onload = function(){
     new Vue({
    el: "#app",
    data: {
      rows: [
        {tag_name:""},
      ]
    },
    methods:{
      addRow: function(event){
        if(event) event.preventDefault()
        this.rows.push({tag_name:""});
      },
      remove: function(row,index){
        if(event) event.preventDefault()
        this.rows.splice(index,1)
      },
    }
  });
}
</script>
{% endblock %}

</head>
{% block content %}
<body style="padding:10%">

  <div class="content container">
      <header class="page-header">
          <h1>관심사 추가하기</h1>
      </header>

      <div class="row">
          <div class="col-md-12">
              <form method="POST" enctype="multipart/form-data" class="form_layout" >
                  {% csrf_token %}

                <div id="app">
                  <table class="table">
                    <thead>
                      <tr>
                        <td><strong>관심사</strong></td>
                        <td><button class="btn btn-primary" @click="addRow" v-on:submit.prevent>추가하기</button></td>
                      </tr>
                    </thead>
                    <tbody>
                      <tr v-for="(row,index) in rows" v-bind:key="row.id" v-on:remove="rows.splice(index, 1)">
                        <td><input v-model="row.tag_name" type="text" name="tag_name" class="form-control" id="tag_name" placeholder="관심사를 입력"></td>
                        <td><button class="btn btn-primary" @click="remove(row,index)" >Remove</button></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                
            <button type="submit" class="btn btn-success">제출</button>
          </form>
          </div>
      </div>
  </div>
</body>
{% endblock%}
</html>

resume_prac/templates/resume_prac/header.html
{% load staticfiles %}


<head>
  {% block title %}{% endblock %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static "resume_prac/core.css" %}">
  {% block extra_head%}{% endblock%}

  <script src="https://unpkg.com/vue"></script>
  <script src="https://use.fontawesome.com/b508397298.js"></script>
</head>


<body>
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/resume">MYR</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/resume">전체보기 <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link btn btn-outline-success my-2 my-sm-0" href="/resume/write">이력서 작성하기</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'resume:example' 1 %}">템플릿 1 보기<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'resume:example' 2 %}">템플릿 2 보기 <span class="sr-only"></span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'resume:search' %}" method="get" accept-charset="utf-8">
       <input class="form-control mr-sm-2 searchfield" id="searchbox" name="q" type="text" placeholder="이름/직업으로 검색">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
      </div>
    </nav>
{% block content %}
{% endblock %}

</body>

resume_prac/templates/resume_prac/resume_detail.html
{% extends "resume_prac/header.html" %}

{% load staticfiles %}

<html>
<head>
  {% block title %} <title>{{ person.person_name }} </title> {% endblock %}
  {% block extra_head%} <link rel="stylesheet" href="{% static "resume_prac/detail.css" %}">
  {% endblock%}
</head>
<body>

{% block content %}
<div class="content container">
  <div class="row">

      <div class="col-md-2" >
          <img src="{{person.profile_image.url}}" alt="프로필사진" class="rounded-circle img-thumbnail img-fluid center-cropped">
      </div>

      <div class="col-md-10">
            <h1>{{person.person_name}} </h1>
            <h5><span class="badge badge-pill badge-success">{{person.position}}</span></h5>
            <a href="{{ person.fb_url }}"  target="_blank"><i class="fa fa-facebook-official" aria-hidden="true" ></i></a>
            <a href="{{ person.gb_url }}"  target="_blank"><i class="fa fa-github-alt" aria-hidden="true"></i></a>
      </div>

      <div class="col-md-12">
            <hr>
      </div>

      <div class="col-md-12">
            <h5 class="oneline">{{ person.person_oneline }}</h5>
      </div>
  </div>

    <div class="row" style="margin-top: 40px">

        <div class="col-md-12">
            <div>
              <i class="fa fa-grav" aria-hidden="true"> 소개</i>
              <hr> <!-- 선 -->
              <p >{{ person.person_desc }}</p>
            </div>
        </div>


        {% if experience %}
        <div class="col-md-12">
            <div>
              <i class="fa fa-database" aria-hidden="true"> 타임라인</i>
              <hr> <!-- 선 -->

              <div class="timeline">
                {% for ex in experience %}
                <div class="entry">
                  <div class="title">
                    <h3> {{ex.startDate.year}}.{{ex.startDate.month}} - {{ex.endDate.year}}.{{ex.endDate.month}}</h3>
                    <p> {{ex.ex_name}}</p>
                  </div>
                  <div class="body">
                    <p>{{ ex.ex_desc }}</p>
                    {% if ex.ex_sub %}
                    <p class="sub">{{ ex.ex_sub}}</p>
                    {% else %}
                    <p class="sub">타임라인입니다.</p>
                    {% endif%}
                  </div>
                </div>
                  {% endfor%}
              </div>
            </div>
        </div>
        {% endif %}


        <div class="col-md-12">
            <div>
              <i class="fa fa-heart" aria-hidden="true"> 스킬</i>
              <hr>
            </div>
        </div>

        <div class="col-md-12">
            <div>
              {% for sk in person.skill_set.all%}
              <h4>{{ sk.devstack }}
                 <div class="progress" style="margin-top:10px">
                   <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: {% widthratio sk.degree 100 100 %}%" aria-valuenow="{% widthratio sk.degree 100 100 %" aria-valuemin="0" aria-valuemax="100">{{sk.degree}}%</div>
                 </div>
               </h4>
              {% endfor %}
            </div>
        </div>

        <div class="col-md-12">
            <div>
              <i class="fa fa-hashtag" aria-hidden="true"> 관심사</i> <i class="fa fa-pencil" aria-hidden="true"></i><a href="/resume/{{person.id}}/add"><i class="fa fa-plus-circle" aria-hidden="true"></i></a>
              <hr>
            </div>
            <div>
              {% for t in person.tag_set.all%}
            <span class="badge badge-pill badge-info">{{ t.tag_name }} </span>
              {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock %}
</body>

</html>

resume_prac/templates/resume_prac/resume_detail_2.html
{% extends "resume_prac/header.html" %}

{% load staticfiles %}

<html>
<head>
  {% block title %} <title>{{ person.person_name }} </title> {% endblock %}
  {% block extra_head%}
  <link rel="stylesheet" href="{% static "resume_prac/detail3.css" %}">
  {% endblock%}
</head>
<body>

{% block content %}

  <div class="container">

    <div class="left_div" >
        <img src="{{person.profile_image.url}}" alt="프로필사진" class="rounded-circle img-fluid center-cropped" >
        <p class="position">{{ person.position }}</p>
        <div class="pages">
          <a href="{{ person.fb_url }}"  target="_blank"><i class="fa fa-facebook-official" aria-hidden="true" ></i></a>
          <a href="{{ person.gb_url }}"  target="_blank"><i class="fa fa-github-alt" aria-hidden="true"></i></a>
        </div>
        <hr>
        <p class="title_1">한마디</p>
        <p class="content_left">{{ person.person_oneline}}</p>
        <hr>
        <p class="title_2">ABOUT</p>
        <p class="content_left">{{ person.person_desc }}</p>
        <hr>
    </div>

    <div class="right_div">

      <p class="title_3"> · TIMELINE · </p>

      <div class="card-div">
      {% for ex in experience %}
      <div class="card" >
        <div class="card-block">
          <h4 class="card-title">{{ ex.ex_name }}</h4>
          {% if ex.endDate == ex.publishDate %}
           <p class="card-date"> <i class="fa fa-calendar" aria-hidden="true"></i>  {{ex.startDate.year}}.{{ex.startDate.month}} - Current </p>
          {% else %}
           <p class="card-date"> <i class="fa fa-calendar" aria-hidden="true"></i>  {{ex.startDate.year}}.{{ex.startDate.month}} - {{ex.endDate.year}}.{{ex.endDate.month}}</p>
          {% endif %}
          <p class="card-text">{{ ex.ex_desc }}</p>
        </div>
      </div>
      {% endfor%}
    </div>

      <p class="title_3"> · SKILL · </p>
        <div class="card-div">
        {% for sk in person.skill_set.all %}
          <div class="card" >
            <div class="card-block">
              <h4 class="card-title">{{ sk.devstack }}</h4>
              <p class="card-date"> <i class="fa fa-signal" aria-hidden="true"></i>  {{ sk.degree }}% </p>
            </div>
          </div>
        {% endfor%}
        </div>

      <p class="title_3"> · INTEREST · </p>
      <div class="card-div">
        {% for t in person.tag_set.all%}
          <span class="badge badge-pill badge-info"> {{ t.tag_name }} </span>
        {% endfor %}
      </div>
    </div>
  </div>


{% endblock %}
</body>

</html>

resume_prac/templates/resume_prac/resume_list.html
{% extends "resume_prac/header.html" %}
{% load staticfiles %}

<html>
<head>
    {% block title %} <title> 이력서 목록 </title> {% endblock %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/vue"></script>

</head>
{% block content %}
<body>
    <div class="container" style="margin-top:100px">
      <div class="starter-template">
        {% for resume in resume_list %}
            <a href="/resume/{{resume.id}}">
                <h5 style="margin-top:20px"> <span class="badge badge-primary">{{resume.position}}</span> {{ resume.person_name }}의 Resume
                  {% for t in resume.tag_set.all%}
                   <span class="tags" style="color:  #ea094f; font-size: 12px;"> #{{t.tag_name}}</span>
                   {% endfor %}
                 </h5>
            </a>
        {% endfor %}
      </div>
    </div>
</body>
{% endblock %}
</html>

resume_prac/templates/resume_prac/resume_write.html
{% extends "resume_prac/header.html" %}
{% load staticfiles %}

<html>
<head>
  {% block title %} <title>Resume</title> {% endblock %}

  {% block extra_head%}
  <link rel="stylesheet" href="{% static "resume_prac/write.css" %}">
  {% endblock%}

</head>

{% block content %}
<body style="padding:10%">
<div class="content container">
    <header class="page-header">
        <h1>Personal Info</h1>
    </header>
    <div class="row">
        <div class="col-md-12">
            <form method="POST" enctype="multipart/form-data" class="form_layout" >
                {% csrf_token %}
                <div class="form-group">
                    <label for="name">이름</label>
                    <input type="text" name="name" class="form-control" id="name" placeholder="이름" required>
                </div>
                <div class="form-group">
                    <label for="position">직군</label>
                    <input type="text" name="position" class="form-control" id="position" placeholder="직군" required>
                </div>
                <div class="form-group">
                    <label for="fb">facebook 주소</label>
                    <input type="text" name="fb" class="form-control" id="fb" placeholder="ex) www.fb.me/">
                </div>
                <div class="form-group">
                    <label for="gb">github 또는 블로그 주소</label>
                    <input type="text" name="gb" class="form-control" id="gb" placeholder="ex) github.com/junebuug">
                </div>
                <div class="form-group">
                    <label for="profile_image">프로필 사진 업로드</label>
                     <input id="profile_image" type="file" class="form-control" name="profile_image">
                </div>
                <div class="form-group">
                    <label for="oneline">한마디</label>
                    <input type="text" name="oneline" class="form-control" id="oneline" placeholder="한마디를 적어주세요.">
                </div>
                <div class="form-group">
                    <label for="introduction">소개</label>
                    <textarea name="introduction" class="form-control" id="introduction" placeholder="소개를 적어주세요." rows="5" required></textarea>
                </div>
              <button type="submit" class="btn btn-success">다음 (경력 입력)</button>
            </form>

        </div>
    </div>
</div>

{% endblock %}

</body>
</html>

resume_prac/templates/resume_prac/resume_write_2.html
{% extends "resume_prac/header.html" %}
{% load staticfiles %}

<html>
<head>
  {% block title %} <title>경력 쓰기 </title> {% endblock %}

  {% block extra_head%}
  <script>

  window.onload = function(){

  new Vue({
   el: "#bpp",
   data: {
     rows: [
       { startDate: "",endDate: "",title: "",desc: "" },
     ]
   },
   methods:{
     addRow2: function(event){
       if(event) event.preventDefault();
       this.rows.push({startDate: "",endDate: "",title:"",desc:""});
     },
     remove2: function(row,index){
       if(event) event.preventDefault();
       this.rows.splice(index,1)
     },
   }
   });
  }

</script>
{% endblock%}

</head>

{% block content %}
<body style="padding:10%">
<div class="content container">
    <header class="page-header">
        <h1>경력 작성</h1>
    </header>
    <div class="row">
        <div class="col-md-12">
            <form method="POST" enctype="multipart/form-data" class="form_layout" >
                {% csrf_token %}


              <div id="bpp">
                <table class="table">
                  <thead>
                    <tr>
                      <td><strong>시작 날짜</strong></td>
                      <td><strong>종료 날짜</strong></td>
                      <td><strong>경력/경험 이름</strong></td>
                      <td><strong>설명</strong></td>
                      <td><button class="btn btn-primary" @click="addRow2" v-on:submit.prevent>추가하기</button></td>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="(row,index) in rows" v-bind:key="row.id" v-on:remove="rows.splice(index, 1)">
                      <td><input v-model="row.startDate" type="date" name="startDate" class="form-control" id="startDate" placeholder="시작일을 입력하세요."></td>
                      <td><input v-model="row.endDate" type="date" name="endDate" class="form-control" id="endDate" placeholder="종료일을 입력하세요."/></td>
                      <td><input v-model="row.title" type="text" name="title" class="form-control" id="title" placeholder="경력명을 입력하세요."/></td>
                      <td><input v-model="row.desc" type="text" name="desc" class="form-control" id="desc" placeholder="경력을 설명해주세요."/></td>
                      <td><button class="btn btn-primary" @click="remove2(row,index)" v-on:submit.prevent >Remove</button></td>
                    </tr>
                  </tbody>
                </table>
              </div>


              <button type="submit" class="btn btn-success">다음(기술 스택 입력)</button>
            </form>

        </div>
    </div>
</div>

{% endblock %}

</body>
</html>

resume_prac/templates/resume_prac/resume_write_3.html
{% extends "resume_prac/header.html" %}
{% load staticfiles %}

<html>
<head>
  {% block title %} <title>기술 스택 입력하기 </title> {% endblock %}

  {% block extra_head%}
  <script>

  window.onload = function(){
     new Vue({
    el: "#app",
    data: {
      rows: [
        {skill: "",degree: 0},
      ]
    },
    methods:{
      addRow: function(event){
        if(event) event.preventDefault()
        this.rows.push({skill:"",degree: 0});
      },
      remove: function(row,index){
        if(event) event.preventDefault()
        this.rows.splice(index,1)
      },
    }
  });


  }

</script>
{% endblock%}

</head>

{% block content %}
<body style="padding:10%">
<div class="content container">
    <header class="page-header">
        <h1>기술 스택 입력하기</h1>
    </header>
    <div class="row">
        <div class="col-md-12">
            <form method="POST" enctype="multipart/form-data" class="form_layout" >
                {% csrf_token %}

              <div id="app">
                <table class="table">
                  <thead>
                    <tr>
                      <td><strong>기술 스택</strong></td>
                      <td><strong>기술 능숙도</strong></td>
                      <td><button class="btn btn-primary" @click="addRow" v-on:submit.prevent>추가하기</button></td>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="(row,index) in rows" v-bind:key="row.id" v-on:remove="rows.splice(index, 1)">
                      <td><input v-model="row.skill" type="text" name="skill" class="form-control" id="skill" placeholder="추가하고 싶은 기술 스택을 적어주세요."></td>
                      <td><input v-model="row.degree" input class="form-control" type="number" value="0" name ="skill_degree" id="skill_degree"/></td>
                      <td><button class="btn btn-primary" @click="remove(row,index)" >Remove</button></td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <button type="submit" class="btn btn-success">등록</button>
            </form>

        </div>
    </div>
</div>

{% endblock %}

</body>
</html>